Repository swiss-seismological-service/scdetect, pull requests merged in 2022-08, with the labels that each got.

#124 Update Offline-Playback.rst
  doc/base/Offline-Playback.rst
Labels: documentation

#126 Fix phase association
  src/apps/cc/config/detector.cpp
  src/apps/cc/config/validators.cpp
  src/apps/cc/detector/linker/pot.cpp
Labels: bug, detection

#132 Add result summary
  doc/base/Offline-Playback.rst
Labels: documentation, enhancement
